# Generated by Django 3.2.25 on 2024-07-20 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wine_tasting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winetastingproduct',
            name='category',
        ),
    ]
