# Generated by Django 3.2.25 on 2024-07-21 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wine_tasting', '0002_remove_winetastingproduct_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='WineTastingBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_requirements', models.TextField(null=True)),
                ('number_of_people', models.IntegerField()),
                ('contact_number', models.CharField(max_length=25)),
                ('selected_date', models.DateTimeField()),
                ('wine_tasting_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wine_tasting.winetastingproduct')),
            ],
        ),
    ]
