# Generated by Django 3.2.25 on 2024-07-23 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20240706_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discounted_price',
            new_name='original_price',
        ),
    ]
